name: ci

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0-30 0-3 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "mollin15@outlook.com"
          git config --local user.name "mollins"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "emo"
          git push
